development:
  cloud_name: ocho-y-medio
  api_key: '461157196653871'
  api_secret: NYgsUTLcNEwX-mqaJBJ23_SOd44
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ocho-y-medio
  api_key: '461157196653871'
  api_secret: NYgsUTLcNEwX-mqaJBJ23_SOd44
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ocho-y-medio
  api_key: '461157196653871'
  api_secret: NYgsUTLcNEwX-mqaJBJ23_SOd44
  enhance_image_tag: true
  static_image_support: false
